### ISSUE TITLE
Main API Functions checklist

### ISSUE THREAD

**Issue by ChetanMandur** [khaiqtran13/dcms#12]
## **Receptionist UI**
- [x] Add patient info
  - Get: All patient info
  - Send: Status (OK or not)
- [x] Edit patient info
  - Get: New info of patient
  - Send: Status (OK or not)
- [x] Set patient appointments
  - Get: Appointment info
  - Send: Status (OK or not)
   
## **Dentists/Hygienist UI**
- [x] Retrieve records of appointed patients easily
  - Get: User ID
    - (User, user_id) -> (Employee, record_id) -> (Records, patient_id) -> List of Records w/ correct record_id
  - Send: List of patients
  
## **Patient UI** 
- [x] Access medical history
  - Get: User ID
    - (User, user_id) -> (Patient, record_id) -> List of records
  - Send: List of records
- [x] Check upcoming appointments
  - Get: User ID
    - (User, user_id) -> (Patient, patient_id) -> List of appointments
  - Send: List of appointments
- [x] #17
  - Get: Info for the appointment request
    - (User, user_id) -> (Patient, patient_id) -> Gets patient_id
    - (User, user_id) -> Get list of dentists
  - Send: Status (OK or not)
 - [x] #18
   - Get: Reviews
     - (User, user_id) -> (Patient, patient_id) -> reviews
   - Send: Status (OK or not)
